apiVersion: v1
kind: Service
metadata:
  name: blockchain-api-backend
spec:
  selector:
    app: blockchain-api
    component: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
