apiVersion: v1
kind: Service
metadata:
  name: blockchain-api-frontend
spec:
  selector:
    app: blockchain-api
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
